name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t alta-project .

    - name: Log in to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Push Docker image to AWS EC2
      run: |
        eval $(aws ecr get-login --no-include-email --region ap-southeast-1)
        docker tag alta-project mlinkaja111/alta-project
        docker push mlinkaja111/alta-project

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: 18.141.175.116
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          docker stop testing2 || true
          docker rm testing2 || true
          docker run -d --name testing2 -p 8080:8080 mlinkaja111/alta-project
